[tool.poetry]
name = "template-matching-api"
version = "0.1.0"
description = ""
authors = ["lukas.bauer <lukas.bauer@resistant.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
